"""Create Columns status quantity price e cost

Revision ID: 16e77179fa13
Revises: 35def3591b28
Create Date: 2022-03-07 02:04:28.871284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e77179fa13'
down_revision = '35def3591b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.add_column('orders_products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('orders_products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('orders_products', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_products', 'cost')
    op.drop_column('orders_products', 'price')
    op.drop_column('orders_products', 'quantity')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
