"""Create columns price and cost in table orders_products

Revision ID: 24477d5d2afe
Revises: a27168ee0a70
Create Date: 2022-03-04 23:43:22.187748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24477d5d2afe'
down_revision = 'a27168ee0a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('orders_products', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('orders_products', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_products', 'cost')
    op.drop_column('orders_products', 'price')
    op.drop_column('orders_products', 'quantity')
    # ### end Alembic commands ###
