"""Inventory's value collumn changed to float

Revision ID: 526dd995a960
Revises: 9f6a0f43d092
Create Date: 2022-03-03 14:15:09.340505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526dd995a960'
down_revision = '9f6a0f43d092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
